#!/usr/bin/env python3
"""Prepare LISFLOOD-FP files for big square 180x180, with subgrid channel from drains"""
import pathlib, json, numpy as np, rasterio, geopandas as gpd
from shapely.geometry import box
import xml.etree.ElementTree as ET

BASE=pathlib.Path(__file__).parent.parent
INPUT=BASE/"input"
BBOX=(80.15,13.08,80.20,13.13)

# Already copied dem etc, now create LISFLOOD specific
def create_channel_rasters():
    # Create channel width/depth rasters from drains
    with rasterio.open(INPUT/"dem_clipped.tif") as ds:
        rows, cols=ds.height, ds.width
        tr=ds.transform
        dem=ds.read(1)
    # Load drains geojson to get width/depth per feature, rasterize weighted
    drains=gpd.read_file(INPUT/"drains_clipped.geojson")
    # For each drain, we have width/depth? Our clipped drains lost width/depth (we stored only ward/objectid)
    # Need to re-parse KML to get width/depth for those drains in BBOX
    # Instead, we will assign average width 0.6 m depth 0.6 m for all drain cells (from earlier stats mean 0.588)
    # But better to re-parse KML for actual per-drain values within BBOX
    KML="/home/cac/Storage/coding/projects/matsya/c4907fed-934b-4342-a3f4-74226853719d.kml"
    # Build dict objectid -> (wid,dep)
    wid_dep={}
    ctx=ET.iterparse(KML, events=('end',))
    _,root=next(ctx)
    for ev,elem in ctx:
        if elem.tag.endswith('Placemark'):
            data={}
            for sd in elem.iter():
                if sd.tag.endswith('SimpleData'):
                    data[sd.attrib.get('name')]=(sd.text or "").strip()
            try:
                oid=int(data.get('OBJECTID','0') or 0)
                wid=float(data.get('DRAIN_WID') or 0)
                dep=float(data.get('DRAIN_DEP') or 0)
                if wid<=0: wid=0.5
                if dep<=0: dep=0.5
                wid_dep[oid]=(wid,dep)
            except: pass
            elem.clear(); root.clear()
    # Now rasterize with width/depth
    from rasterio.features import rasterize
    import shapely.geometry as geom
    # Create width and depth rasters initialized 0
    width_raster=np.zeros((rows,cols), dtype=np.float32)
    depth_raster=np.zeros((rows,cols), dtype=np.float32)
    # For each drain feature, burn its wid/dep
    for _, row in drains.iterrows():
        oid=row['objectid']
        wid,dep=wid_dep.get(oid,(0.6,0.6))
        # Rasterize this single drain
        geom_list=[(row.geometry, 1)]
        mask=rasterize(geom_list, out_shape=(rows,cols), transform=tr, fill=0, dtype='uint8', all_touched=True)
        # Where mask, set width/depth (if multiple drains overlap, take max)
        width_raster[mask==1]=np.maximum(width_raster[mask==1], wid)
        depth_raster[mask==1]=np.maximum(depth_raster[mask==1], dep)
    np.save(INPUT/"channel_width.npy", width_raster)
    np.save(INPUT/"channel_depth.npy", depth_raster)
    print(f"Channel width mean {width_raster[width_raster>0].mean():.3f} max {width_raster.max():.3f} cells { (width_raster>0).sum()}")
    print(f"Channel depth mean {depth_raster[depth_raster>0].mean():.3f} max {depth_raster.max():.3f}")
    # Also save as tif for LISFLOOD
    with rasterio.open(INPUT/"dem_clipped.tif") as ds:
        prof=ds.profile
    prof.update(dtype='float32', count=1, compress='lzw', nodata=0)
    with rasterio.open(INPUT/"channel_width.tif",'w',**prof) as dst:
        dst.write(width_raster,1)
    with rasterio.open(INPUT/"channel_depth.tif",'w',**prof) as dst:
        dst.write(depth_raster,1)
    # Create LISFLOOD .par file
    par_content=f"""# LISFLOOD-FP 8.0 parameter file - MATSYA big square 180x180 @30m
# Generated by prepare_lisflood.py

DEMfile         dem_clipped.tif
# LISFLOOD expects ASCII .asc, but we provide GeoTIFF and will convert in run
nx              {cols}
ny              {rows}
dx              30.0
dy              30.0
# Manning
manningfile     roughness.tif  # we will generate from roughness.npy
# Channel
chanfile        channel_width.tif  # placeholder, LISFLOOD uses separate chan par
chan_width      mean {width_raster[width_raster>0].mean():.3f}
chan_depth      mean {depth_raster[depth_raster>0].mean():.3f}
# Rainfall
rainfile        rainfall.txt
# Time
tstart          0
tend            21600
dt              0.5
# Output
dirroot         output/
resultfile      res
# etc
"""
    (INPUT/"cas"/"lisflood.par").write_text(par_content)
    # Roughness tif
    rough=np.load(INPUT/"roughness.npy")
    with rasterio.open(INPUT/"dem_clipped.tif") as ds:
        prof=ds.profile
    prof.update(dtype='float32', count=1, compress='lzw', nodata=-9999)
    with rasterio.open(INPUT/"roughness.tif",'w',**prof) as dst:
        dst.write(rough.astype(np.float32),1)
    # Rainfall txt same as TELEMAC
    (INPUT/"cas"/"rainfall.txt").write_text("# time rain\n"+"".join(f"{t} 50.0\n" for t in range(0,3601,300))+"3900 0.0\n21600 0.0\n")
    print(f"LISFLOOD par, roughness tif, channel tifs written to {INPUT}")

if __name__=="__main__":
    create_channel_rasters()
    print("LISFLOOD prepare done")
